import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const poppins = localFont({
//   src: "./fonts/Poppins-Bold.ttf",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Alv's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <head>
        <script>AOS.init();</script>
      </head>
      <body className={`antialiased`}>{children}</body>
    </html>
  );
}
